### ISSUE TITLE
serves on port 8080 but not port 80

### ISSUE THREAD

**Issue by isomorphisms** [http-party/http-server#105]
```
ubuntu@domU-12-31-39-09-9A-6D:~$ http-server -p 80

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1023:19)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
ubuntu@domU-12-31-39-09-9A-6D:~$ http-server
Starting up http-server, serving ./ on: http://0.0.0.0:8080
Hit CTRL-C to stop the server
^Chttp-server stopped.
```

**Comment by moubry** [comment]
To use `http-server` over port 80, you need to run with the privileges of the root user:

```
$ sudo http-server -p 80
```

**Comment by yanickrochon** [comment]
I ended up creating a proxy host with nginx and everything is fine. The port 80 requires, indeed, elevated privileges.
