### ISSUE TITLE
SSL options fail when attempting to grab cert

### ISSUE THREAD

**Issue by hwatersiv** [http-party/http-server#535]
running ssl is causing an error:

 http-server build/ -p 4200 --silent --ssl --cert sslcert/cert.pem --key sslcert/key.pem

**What did you expect to happen?**
that my cert would be excepted and i would be able to run my app

**What actually happened? Please include the actual error trace and / or stack trace if applicable.**

```
> http-server build/ -p 4200 --silent --ssl --cert sslcert/cert.pem --key sslcert/key.pem

_tls_common.js:134
      c.context.setCert(cert);
                ^

Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:134:17)
    at Server.setSecureContext (_tls_wrap.js:1013:27)
    at Server (_tls_wrap.js:893:8)
    at new Server (https.js:61:14)
    at Object.createServer (https.js:84:10)
    at Object.core.createServer (...\node_modules\union\lib\core.js:93:18)
    at new HttpServer (...\node_modules\http-server\lib\http-server.js:134:23)
    at Object.exports.createServer (...\node_modules\http-server\lib\http-server.js:20:10)
    at listen (...\node_modules\http-server\bin\http-server:123:27)
    at Object.<anonymous> (...\node_modules\http-server\bin\http-server:92:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Tell us about your environment**
Windows 10 Prop 64-Bit (10.0, build 17134)

- **http-server version:**
0.11.1
- **Platform:**
node v11.13.0
npm 6.7.0

**Additional info**
This error only occurs after I resolve the high vulnerability error (I assume with ecstatic dependency);

**Comment by thornjad** [comment]
@hwatersiv could you check if this still happens on version 0.12.0? This may have been fixed

**Comment by thornjad** [comment]
Closing under the assumption this is now fixed, please reopen if this is not the case

**Comment by dcolakchile** [comment]
Still happening.

**Comment by EKashpersky** [comment]
The error still there

**Comment by EKashpersky** [comment]
node@15.0.1
http-server@0.12.3
