### ISSUE TITLE
Tests not passing on master. 

### ISSUE THREAD

**Issue by dwjohnston** [http-party/http-server#721]
**Steps to reproduce the issue, if applicable. Include the actual command and output and/or stack trace.**

```
git clone git@github.com:http-party/http-server.git
npm i
npm test
```
**What did you expect to happen?**

The tests pass. 

The tests are not passing: 

```
354 passing (16s)
  17 failing

  1) test/main.test.js http-server main should be equal:

      Error: should be equal
      + expected - actual

      -204
      +405

      at Promise.all.requestAsync.then.res (test/main.test.js:83:17)

  2) test/main.test.js http-server main TypeError: Cannot read property 'split' of undefined:
     Error: TypeError: Cannot read property 'split' of undefined
      at Promise.all.requestAsync.then.catch.err (test/main.test.js:88:31)

  3) test/main.test.js http-server main should be equal:

      Error: should be equal
      + expected - actual

      -200
      +404

      at Promise.all.requestAsync.then.res (test/main.test.js:70:17)

  4) test/main.test.js http-server main should be equal:

      Error: should be equal
      + expected - actual

      -200
      +404

      at Promise.all.requestAsync.then (test/main.test.js:44:17)

  5) test/main.test.js http-server main should be equal:

      Error: should be equal
      + expected - actual

      -200
      +404

      at Promise.all.requestAsync.then.res (test/main.test.js:113:17)

  6) test/main.test.js http-server main should match pattern provided:

      Error: should match pattern provided
      + expected - actual

      -/^text\/html/
      +undefined

      at Promise.all.requestAsync.then.res (test/main.test.js:114:17)

  7) test/main.test.js http-server main should be equal:

      Error: should be equal
      + expected - actual

      -200
      +404

      at Promise.all.requestAsync.then.res (test/main.test.js:98:17)

  8) test/main.test.js http-server main should be equal:
     Error: should be equal
      at Promise.all.requestAsync.then.res (test/main.test.js:99:17)

  9) test/main.test.js http-server main should be equal:

      Error: should be equal
      + expected - actual

      -200
      +404

      at Promise.all.requestAsync.then.res (test/main.test.js:108:17)

  10) test/main.test.js http-server main should be equal:
     Error: should be equal
      at Promise.all.requestAsync.then.res (test/main.test.js:109:17)

  11) test/main.test.js http-server main should match pattern provided:

      Error: should match pattern provided
      + expected - actual

      -"/file"

<snip>

  13) test/main.test.js http-server main should be equal:
     Error: should be equal
      at Promise.all.requestAsync.then.res (test/main.test.js:64:17)

  14) test/main.test.js http-server main should be equal:
     Error: should be equal
      at Promise.all.requestAsync.then.res (test/main.test.js:65:17)

  15) test/main.test.js http-server main root file content matches:

      Error: root file content matches
      + expected - actual

      +hello, I know nodejitsu

      at Promise.all.requestAsync.then (test/main.test.js:47:17)

  16) test/main.test.js http-server main should be equal:

      Error: should be equal
      + expected - actual

      -200
      +404

      at requestAsync.then (test/main.test.js:140:21)

  17) test/main.test.js http-server main proxy fallback root file content matches:

      Error: proxy fallback root file content matches
      + expected - actual

      +hello, I know nodejitsu

      at requestAsync.then (test/main.test.js:144:21)

```

**If the issue is a feature request, what is the motivation / use case for it?**

**Tell us about your environment**
- **exact http-server version:** (Source code 13.0.0)
- **Node version:** 10.23.0
- **Platform:** MacOS

**Other information (related issues, suggestions for a fix, etc):**

**Comment by dwjohnston** [comment]
Never mind, I had another process running on port 8080. :|
