### ISSUE TITLE
[Error] TypeError: Readable.from is not a function

### ISSUE THREAD

**Issue by imgonewild** [http-party/http-server#755]
I'm building a new angular project and add @angular/pwa package, install http-server to my project
I got TypeError: Readable.from is not a function error

#### Environment Versions

OS Type: Windows 7 Pro
Node version: V12.2.0
http-server version: V14.0.0

#### Steps to reproduce

1. ng new pwa
2. ng @angular/pwa
3. npm install http-server
4. ng build --prod
5. http-server

```
(Starting up http-server, serving ./public

http-server version: 14.0.0

http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://192.168.16.91:8080
  http://192.168.56.1:8080
  http://192.168.99.1:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server)
```

but after opened the http://192.168.16.91:8080
I got the errors in vsc terminal as below, and the web page remained blank.

```
[2021-10-22T09:43:28.096Z]  "GET /" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36"
(node:1996) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
C:\Users\alan_yu\AppData\Roaming\npm\node_modules\http-server\lib\core\index.js:246
          stream = Readable.from(bytes)
                            ^

TypeError: Readable.from is not a function
    at serve (C:\Users\alan_yu\AppData\Roaming\npm\node_modules\http-server\lib\core\index.js:246:29)
    at C:\Users\alan_yu\AppData\Roaming\npm\node_modules\http-server\lib\core\index.js:419:13
    at FSReqCallback.oncomplete (fs.js:149:5)
```

**Comment by Inchill** [comment]
I met the same error and the answer is helpful, thanks all:)
